version: "3"
services:
  node-app:
    container_name: node-app-container
    volumes:
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    environment:
    - PORT=4000
    env_file:
      - .env
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example